---
string[] list                 # The requested list of strings
bool success                  # indicate successful run of service
string message                # informational, e.g. for error messages
