uint32 seq     # scan position number within a project, starting with 1, 0 is the current scan position
---
sensor_msgs/PointCloud2 pointcloud
bool success   # indicate successful run of service
string message # informational, e.g. for error messages
